repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.github/workflows/.*\.yml$
      - id: end-of-file-fixer
        exclude: ^\.github/workflows/.*\.yml$
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        files: ^(src|tests)/
        args: ["--line-length=88"]
      - id: ruff-format
        files: ^(src|tests)/
