---
name: UI Bridge

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar detalhes do runner
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repo: $GITHUB_REPOSITORY"
      - name: Summary
        if: ${{ always() }}
        run: |
          echo "# UI Bridge" >> "$GITHUB_STEP_SUMMARY"
          echo "- Repo: $GITHUB_REPOSITORY" >> "$GITHUB_STEP_SUMMARY"
          echo "- Runner OS: $RUNNER_OS" >> "$GITHUB_STEP_SUMMARY"